# Generated by Django 4.0.6 on 2022-07-07 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokenativacao',
            name='token',
            field=models.CharField(max_length=64),
        ),
    ]
